name: Pull Request Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install node-fetch@2
        run: npm install node-fetch@2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy preview
        uses: JamesIves/github-pages-deploy-action@4.1.3
        id: deploy_preview
        with:
          branch: gh-pages
          folder: build

      - name: Add preview link to pull request description
        uses: actions/github-script@v5
        with:
          script: |
            const previewLink = `Preview URL: ${{ steps.deploy_preview.outputs.url }}`;
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            octokit.rest.issues.listComments({
              owner,
              repo,
              issue_number: number
            }).then(({ data: comments }) => {
              const existingComment = comments.find(
                comment => comment.user.login === 'github-actions[bot]'
              );

              if (existingComment) {
                octokit.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: existingComment.id,
                  body: previewLink
                });
              } else {
                octokit.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: number,
                  body: previewLink
                });
              }
            });
