name: Pull Request Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Check if pull request is closed
        id: check_pr
        run: echo "::set-output name=closed::$(echo ${GITHUB_EVENT_NAME} == 'pull_request' && echo ${GITHUB_EVENT_ACTION} == 'closed')"

      - name: Build React app
        id: build
        run: npm run build
        if: steps.check_pr.outputs.closed != 'true'

      - name: Deploy preview
        uses: JamesIves/github-pages-deploy-action@4.1.3
        id: deploy_preview
        with:
          branch: gh-pages
          folder: build
        if: steps.check_pr.outputs.closed != 'true'

      - name: Add preview link to pull request description
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewLink = `Preview URL: ${{ steps.deploy_preview.outputs.url }}`;
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            octokit.rest.issues.listComments({
              owner,
              repo,
              issue_number: number,
            }).then(({ data: comments }) => {
              const comment = comments.find(
                (comment) =>
                  comment.user.login === "github-actions[bot]" &&
                  comment.body.includes("Preview URL:")
              );

              if (comment) {
                octokit.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: comment.id,
                  body: previewLink,
                });
              } else {
                octokit.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: number,
                  body: previewLink,
                });
              }
            });
